"""add_age_group_to_rooms

Revision ID: 82cec1c583b5
Revises: 29ebaef06b44
Create Date: 2025-06-30 16:00:24.569572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cec1c583b5'
down_revision: Union[str, None] = '29ebaef06b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('age_group', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'age_group')
    # ### end Alembic commands ###
