"""add_player_status_and_timeout_fields

Revision ID: 90d3c8043be8
Revises: 80d22484ede1
Create Date: 2025-06-29 22:31:17.655518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90d3c8043be8'
down_revision: Union[str, None] = '80d22484ede1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rooms_is_public'), table_name='rooms')
    op.drop_index(op.f('ix_user_cards_user_type_number'), table_name='user_cards')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_cards_user_type_number'), 'user_cards', ['user_id', 'card_type', 'card_number'], unique=False)
    op.create_index(op.f('ix_rooms_is_public'), 'rooms', ['is_public'], unique=False)
    # ### end Alembic commands ###
