"""Migrate from firebase_uid to game_center_player_id

Revision ID: 0841f0019348
Revises: 834d9cf03188
Create Date: 2025-06-27 15:28:10.780159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0841f0019348'
down_revision: Union[str, None] = '834d9cf03188'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('game_center_player_id', sa.String(length=128), nullable=False))
    op.drop_index(op.f('ix_users_firebase_uid'), table_name='users')
    op.create_index(op.f('ix_users_game_center_player_id'), 'users', ['game_center_player_id'], unique=True)
    op.drop_column('users', 'firebase_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firebase_uid', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_game_center_player_id'), table_name='users')
    op.create_index(op.f('ix_users_firebase_uid'), 'users', ['firebase_uid'], unique=True)
    op.drop_column('users', 'game_center_player_id')
    # ### end Alembic commands ###
