"""add_connection_status_and_game_timeouts

Revision ID: 29ebaef06b44
Revises: 90d3c8043be8
Create Date: 2025-06-29 22:32:34.741988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ebaef06b44'
down_revision: Union[str, None] = '90d3c8043be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_rounds', sa.Column('selection_deadline', sa.DateTime(), nullable=True))
    op.add_column('game_rounds', sa.Column('voting_deadline', sa.DateTime(), nullable=True))
    op.add_column('game_rounds', sa.Column('auto_advanced', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('room_participants', sa.Column('connection_status', sa.String(length=20), nullable=False, server_default='connected'))
    op.add_column('room_participants', sa.Column('last_activity', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('room_participants', sa.Column('last_ping', sa.DateTime(), nullable=True))
    op.add_column('room_participants', sa.Column('disconnect_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('room_participants', sa.Column('missed_actions', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_participants', 'missed_actions')
    op.drop_column('room_participants', 'disconnect_count')
    op.drop_column('room_participants', 'last_ping')
    op.drop_column('room_participants', 'last_activity')
    op.drop_column('room_participants', 'connection_status')
    op.drop_column('game_rounds', 'auto_advanced')
    op.drop_column('game_rounds', 'voting_deadline')
    op.drop_column('game_rounds', 'selection_deadline')
    # ### end Alembic commands ###
